### ISSUE TITLE
Indent issue on the customization page

### ISSUE THREAD

**Issue by anotien** [getgrav/grav-learn#1118]
Hi, 

The "Inheriting Manually" section on the [Customization ](https://learn.getgrav.org/17/themes/customization#theme-inheritance) page gives the following code snippet:

```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
     - 'user://themes/mytheme'
     - 'user://themes/quark'
```

However, I found in my case that once uploaded to the server, it would make a blank page of both my site and the admin plugin page. 
This seems to be an indent issue, as the following worked:

```
streams:
 schemes:
   theme:
     type: ReadOnlyStream
     prefixes:
       '':
          - 'user/themes/mytheme'
          - 'user/themes/quark'
```

I got the hint from https://getgrav.org/blog/theme-development-with-inheritance where the indent is different than the official documentation.
I have no clue how to rework the docs.md file as it uses a syntax I'm not familiar with, but I thought I'd raise the issue at least.
