### ISSUE TITLE
Multi-Language: language selection by browser unclear/very strict

### ISSUE THREAD

**Issue by nitmws** [getgrav/grav-learn#305]
Maybe this is not only a documentation issue: the Multi-Language page (under Content) indicates that it is possible to select the language by a browser's Accept Language header but it does not describe in detail how this type of content negotiation is processed.

The practical issue with that approach is that most browsers set the value of Accept Language by the localization settings of the underlying operating system. If one installes Chrome in London then "en-gb" is set, if one installes in Boston then "en-us" is set, if one installes in Sidney then "en-au" is set.

On the other hand most makers of a web site will provide only a single page "in English" and not making a destinction between British and US English. 

By my testing Grav does not fall-back to pages created in English (en) if the browser sends "en-gb". 

Therefore this very strict behaviour should be explained in the documentation or the software should be changed to support such a fall-back.

**Comment by flaviocopes** [comment]
Hi, I tested and I'm not noticing this behavior.

I have a `en-GB` page and an `en` page. If I access with `en-US` as accepted language, Grav falls back to `en`.

Example of my system settings:

```
languages:
  supported:
    - en-US
    - en
    - fr
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: true
  override_locale: true
```

**Comment by nitmws** [comment]
What I don't understand in your settings: you write you have pages in en-GB and in en. But your settings show as supported languages en-US, en and fr - but not en-GB??

My system settings:

```
languages:
  supported:
    - de
    - en-GB
    - en
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: true
  override_locale: true
```

The home page of the site is available in de, en and en-GB.
Accessing my website www.newsit.biz with a browser with en-US as its only accepted language shows the home page in German and not in en.
