### ISSUE TITLE
Forms in modular pages (inconsistencies)

### ISSUE THREAD

**Issue by lguariento** [getgrav/grav-learn#425]
Hello,

in https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages there are a few issues.

templates/formdata.html.twig , as far as I can see, is not included in the Antimatter theme. Also, the documentation doesn't say where to copy the form.html.twig (in 'templates/modular' or 'templates'?).

The live example 'The Deliver skeleton' does not represent what is written on the tutorial: see the arrangement of the folders and file names.

Following the instructions given in the documentation page I have managed to have a form displayed in my modular page (which is the home page). The problem is that when I click 'submit' I get the 'Display page not found', even though the form: action: have been properly set.

**Comment by rhukster** [comment]
`formdata.html.twig` is provided by the forms plugin itself. I'll test modular forms again, and ensure it lines up with the docs.

**Comment by lguariento** [comment]
Thanks. I haven't found "templates/formdata.html.twig", as indicated in the documentation. Is "user/plugins/form/templates/forms/data.html.twig" that you're referring to?

**Comment by rhukster** [comment]
Yah probably is a typo in the learn docs.

**Comment by lguariento** [comment]
Still, the whole process described is not consistent with the 'live' example. Also, as I said, I cannot get the post-submit page following these instructions, and I'm quite sure I did all the steps described.

**Comment by rhukster** [comment]
Like i said, i'll go back and double check the docs line up with reality.  I have a modular form working in my test setup, so i just need to make sure the docs are accurate.

**Comment by lguariento** [comment]
Sure :) let me know if there's anything I can test myself or if you need more information.

**Comment by rhukster** [comment]
Would be helpful to see your form you are using (the .md file)

**Comment by lguariento** [comment]
```
form:
    action: /home
    name: contact
    fields:
        -
            name: name
            label: Name
            placeholder: 'Enter your name'
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
        -
            name: message
            label: Message
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            email:
                subject: '[Site Contact Form] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            message: 'Thank you for getting in touch!'
---
```

I put it both in the 'modular.md' page and in the home/_contact/form.md file (as per documentation, paragraph between the '!!!I'. Not at the same time of course!) - same thing.
