### ISSUE TITLE
close_connection set to true or false for debugging?

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-learn#844]
Looking at this page:
https://learn.getgrav.org/16/advanced/debugging
https://github.com/getgrav/grav-learn/blob/develop/pages/08.advanced/03.debugging/docs.md

```yaml
debugger:
  enabled: true                        # Enable Grav debugger and following settings
  shutdown:
    close_connection: true             # Close the connection before calling onShutdown(). false for debugging
```

Why does it say "false for debugging", but the yaml setting is set to true? Should the get fixed or is the doc just confusing?
