### ISSUE TITLE
File upload fields on page blueprints

### ISSUE THREAD

**Issue by davidtrainer** [getgrav/grav-learn#927]
I upgraded to Grav v1.7 and I noticed that a file upload field on one of my page templates would not accept file uploads with the error `An error occurred while trying to upload the file` `Undefined index: *`

Suspecting my page blueprint, I went and found https://learn.getgrav.org/17/forms/blueprints/fields-available#file-field which includes the warning,

> The file field is intended to be used by configuration, theme, and plugins blueprints, NOT page blueprints. For pages, you should use the existing pagemedia field and then utilize the filepicker field to select the files.

Then I found https://learn.getgrav.org/17/forms/blueprints/how-to-add-file-upload and thought it would help me, but it says,

> You can add file upload functionality in Pages, Config, Plugins and Themes blueprints.
> 
> Example of usage:
> 
> custom_file:
>   name: myfile
>   type: file

The `pagemedia` and `filepicker` field types don't seem to allow drag-and-drop uploads. And the docs say I shouldn't use the `file` type. So how do I add a file upload field to a page blueprint?

**Comment by mahagr** [comment]
Are you trying to add a file field into a list? Can you paste your blueprint here?

**Comment by davidtrainer** [comment]
@mahagr Yes, I am trying to add the file field to a list.

Blueprint is as follows:

```
title: Slideshow
form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        Slideshow:
          type: tab
          title: Slideshow
          
          fields:
            header.slides:
              name: slides
              type: list
              title: Slides
              label: Slides
              min: 1
              fields:
                .slide:
                  label: Slide
                  help: Upload an image file to be used in the slideshow.
                  type: file
                  multiple: false
                  destination: '@self'
                  accept:
                    - image/*
```
